{
  "openapi": "3.0.1",
  "info": {
    "title": "MICROSERVICE-development-storefront-web-api-Update Api User By User Id-v1-spec",
    "description": "The User Management API allows for the efficient updating of user profiles via their unique user IDs. This operation is essential for maintaining user data integrity and ensuring that accurate information is readily available within the application. Typical consumers include developers managing user accounts and applications that require real-time user data synchronization. By leveraging this API, organizations can streamline their user management processes and enhance overall user engagement.",
    "version": "1.0",
    "extensions": {
      "x-serviceName": "storefront-web-api"
    }
  },
  "servers": [
    {
      "url": "https://observability-stage-raju.apiwiz.io",
      "description": "Sandbox server",
      "variables": {},
      "x-schema": "https://",
      "x-name": "Sandbox server",
      "x-environmentName": "Sandbox",
      "x-hide": false,
      "x-environmentId": "6ae0dc350d4c405cc4ccb613",
      "x-basePath": "/"
    },
    {
      "url": "http://localhost:5311",
      "description": "development",
      "variables": {},
      "x-schema": "http://",
      "x-name": "development",
      "x-environmentName": "development",
      "x-hide": false,
      "x-environmentId": "6ae0dc440d4c405cc4ccb61c",
      "x-basePath": "/"
    }
  ],
  "paths": {
    "/api/v1/users/{userId}": {
      "patch": {
        "tags": [
          "User Management"
        ],
        "summary": "Update user details",
        "description": "This operation allows you to update the information of a specific user identified by their unique ID. You can modify various attributes such as name, email, and more using this endpoint.",
        "operationId": "updateApiUserByUserId",
        "parameters": [
          {
            "$ref": "#/components/parameters/host"
          },
          {
            "$ref": "#/components/parameters/accept"
          },
          {
            "$ref": "#/components/parameters/user-agent"
          },
          {
            "$ref": "#/components/parameters/x-tenant-id"
          },
          {
            "$ref": "#/components/parameters/content-type"
          },
          {
            "$ref": "#/components/parameters/x-request-id"
          },
          {
            "$ref": "#/components/parameters/content-length"
          },
          {
            "$ref": "#/components/parameters/x-mock-response"
          },
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "requestBody": {
          "description": "A patch request to update the user details for the user with ID 1008. This request body requires certain fields to be provided for modifying user information.",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateApiUserByUserIdRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "The user information was updated successfully.",
            "headers": {
              "Date": {
                "$ref": "#/components/headers/Date"
              },
              "X-Api-Name": {
                "$ref": "#/components/headers/X-Api-Name"
              },
              "X-Served-By": {
                "$ref": "#/components/headers/X-Served-By"
              },
              "Content-Type": {
                "$ref": "#/components/headers/Content-Type"
              },
              "X-Request-Id": {
                "$ref": "#/components/headers/X-Request-Id"
              },
              "Content-Length": {
                "$ref": "#/components/headers/Content-Length"
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateApiUserByUserIdResponse_200"
                }
              }
            }
          }
        },
        "callbacks": {},
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "servers": []
      },
      "servers": [],
      "parameters": []
    }
  },
  "components": {
    "schemas": {
      "UpdateApiUserByUserIdRequest": {
        "required": [
          "email"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "The email address of the user.",
            "example": "rohan.mehta@acmecorp.com"
          }
        },
        "description": "Schema for the PATCH request body for updating user details.",
        "example": {
          "email": "rohan.mehta@acmecorp.com"
        }
      },
      "UpdateApiUserByUserIdResponse_200": {
        "type": "object",
        "properties": {
          "data": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer",
                "description": "The unique identifier for the user.",
                "format": "int32",
                "example": 0
              },
              "name": {
                "type": "string",
                "description": "The name of the user.",
                "example": "John Doe"
              },
              "email": {
                "type": "string",
                "description": "The email address of the user.",
                "example": "john.doe@example.com"
              },
              "city": {
                "type": "string",
                "description": "The city where the user resides.",
                "example": "New York"
              },
              "plan": {
                "type": "string",
                "description": "The subscription plan of the user.",
                "example": "premium"
              },
              "status": {
                "type": "string",
                "description": "The current status of the user account.",
                "example": "active"
              },
              "memberSince": {
                "type": "string",
                "description": "Date when the user became a member.",
                "example": "2021-01-01"
              },
              "updatedAt": {
                "type": "string",
                "description": "Timestamp of the last update to the user's details.",
                "example": "2023-10-01T12:00:00Z"
              }
            },
            "description": "Contains user details.",
            "example": {
              "id": 1008,
              "name": "Lucas Ferreira",
              "email": "rohan.mehta@acmecorp.com",
              "city": "Sao Paulo",
              "plan": "STANDARD",
              "status": "ACTIVE",
              "memberSince": "2025-05-30",
              "updatedAt": "2026-10-28T14:00:31.808101Z"
            }
          },
          "meta": {
            "type": "object",
            "properties": {
              "requestId": {
                "type": "string",
                "description": "Unique identifier for the request.",
                "example": "req_123456"
              },
              "tenant": {
                "type": "string",
                "description": "Identifier for the tenant making the request.",
                "example": "tenant_1"
              },
              "api": {
                "type": "string",
                "description": "The API endpoint that was requested.",
                "example": "/api/users/1"
              },
              "service": {
                "type": "string",
                "description": "The service that processed the request.",
                "example": "user-service"
              },
              "generatedAt": {
                "type": "string",
                "description": "Timestamp when the meta information was generated.",
                "example": "2023-10-01T12:00:00Z"
              }
            },
            "description": "Contains metadata about the request.",
            "example": {
              "requestId": "req_sgz74e8lsldy",
              "tenant": "acme-retail",
              "api": "patchUser",
              "service": "storefront-web-api",
              "generatedAt": "2026-10-28T14:00:31.808131Z"
            }
          }
        },
        "description": "Response schema for a successful PATCH operation on the user resource. This schema includes user data and meta information about the request.",
        "example": {
          "data": {
            "id": 1008,
            "name": "Lucas Ferreira",
            "email": "rohan.mehta@acmecorp.com",
            "city": "Sao Paulo",
            "plan": "STANDARD",
            "status": "ACTIVE",
            "memberSince": "2025-05-30",
            "updatedAt": "2026-10-28T14:00:31.808101Z"
          },
          "meta": {
            "requestId": "req_sgz74e8lsldy",
            "tenant": "acme-retail",
            "api": "patchUser",
            "service": "storefront-web-api",
            "generatedAt": "2026-10-28T14:00:31.808131Z"
          }
        }
      }
    },
    "parameters": {
      "host": {
        "name": "host",
        "in": "header",
        "required": false,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "example": "localhost:5311"
        },
        "example": "localhost:5311"
      },
      "accept": {
        "name": "accept",
        "in": "header",
        "required": false,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "example": "*/*"
        },
        "example": "*/*"
      },
      "user-agent": {
        "name": "user-agent",
        "in": "header",
        "required": false,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "example": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/126.0 Safari/537.36"
        },
        "example": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/126.0 Safari/537.36"
      },
      "x-tenant-id": {
        "name": "x-tenant-id",
        "in": "header",
        "required": false,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "example": "acme-retail"
        },
        "example": "acme-retail"
      },
      "content-type": {
        "name": "content-type",
        "in": "header",
        "required": false,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "example": "application/json"
        },
        "example": "application/json"
      },
      "x-request-id": {
        "name": "x-request-id",
        "in": "header",
        "required": false,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "example": "3E6D94B7-0D5C-4B93-A1A5-EAE152162152"
        },
        "example": "3E6D94B7-0D5C-4B93-A1A5-EAE152162152"
      },
      "content-length": {
        "name": "content-length",
        "in": "header",
        "required": false,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "example": "37"
        },
        "example": "37"
      },
      "x-mock-response": {
        "name": "x-mock-response",
        "in": "header",
        "description": "Controls x-mock-response response status",
        "required": false,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "enum": [
            "MICROSERVICE_development_200"
          ],
          "default": "MICROSERVICE_development_200"
        }
      },
      "userId": {
        "name": "userId",
        "in": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string"
        }
      }
    },
    "headers": {
      "Date": {
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "example": "Wed, 28 Oct 2026 14:00:31 GMT"
        },
        "example": "Wed, 28 Oct 2026 14:00:31 GMT"
      },
      "X-Api-Name": {
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "example": "patchUser"
        },
        "example": "patchUser"
      },
      "X-Served-By": {
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "example": "storefront-web-api"
        },
        "example": "storefront-web-api"
      },
      "Content-Type": {
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "example": "application/json"
        },
        "example": "application/json"
      },
      "X-Request-Id": {
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "example": "fba02808-aae2-48f5-93b0-5ae87ab56f1e"
        },
        "example": "fba02808-aae2-48f5-93b0-5ae87ab56f1e"
      },
      "Content-Length": {
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "example": "359"
        },
        "example": "359"
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "description": "This security scheme uses Bearer authentication, where the client must provide a valid token in the Authorization header for accessing protected resources.",
        "scheme": "bearer"
      }
    }
  }
}