{
  "openapi": "3.0.1",
  "info": {
    "title": "MICROSERVICE-PROD-Create Banking Enterprise Services Security Assurance Review-v5-spec",
    "description": "MICROSERVICE-PROD-Create Banking Enterprise Services Security Assurance Review-v5-spec",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://prod-workspace-pwmw.apiwiz.io",
      "description": "Sandbox server",
      "variables": {},
      "x-schema": "https://",
      "x-name": "Sandbox server",
      "x-environmentName": "Sandbox",
      "x-hide": false,
      "x-environmentId": "6a7f52236ae9a15654cd5721",
      "x-basePath": "/"
    },
    {
      "url": "http://35.162.152.203:9008",
      "description": "PROD",
      "variables": {},
      "x-schema": "http://",
      "x-name": "PROD",
      "x-environmentName": "PROD",
      "x-hide": false,
      "x-environmentId": "6a784eac1d7e36108cc3cb0c",
      "x-basePath": "/"
    }
  ],
  "paths": {
    "/v5/banking/enterprise-services/security-assurance/{securityAssuranceId}/reviews": {
      "post": {
        "operationId": "createBankingEnterpriseServicesSecurityAssuranceReview",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-mock-response"
          },
          {
            "$ref": "#/components/parameters/securityAssuranceId"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateBankingEnterpriseServicesSecurityAssuranceReviewRequest"
              }
            }
          }
        },
        "responses": {
          "202": {
            "description": "202Description",
            "headers": {
              "X-Endpoint-Id": {
                "$ref": "#/components/headers/X-Endpoint-Id"
              },
              "X-Runtime-App": {
                "$ref": "#/components/headers/X-Runtime-App"
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateBankingEnterpriseServicesSecurityAssuranceReviewResponse_202"
                }
              }
            }
          }
        },
        "callbacks": {},
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "servers": []
      },
      "servers": [],
      "parameters": []
    }
  },
  "components": {
    "schemas": {
      "CreateBankingEnterpriseServicesSecurityAssuranceReviewRequest": {
        "type": "object",
        "properties": {
          "reviewReason": {
            "type": "string",
            "example": "STANDARD"
          },
          "reviewScope": {
            "type": "array",
            "example": [
              "STANDARD"
            ],
            "items": {
              "type": "string",
              "example": "string"
            }
          },
          "assignedReviewerId": {
            "type": "string",
            "example": "STANDARD"
          },
          "dueAt": {
            "type": "string",
            "example": "2026-08-11T12:00:00Z"
          },
          "requestContext": {
            "type": "object",
            "properties": {
              "requestId": {
                "type": "string",
                "example": "string"
              },
              "correlationId": {
                "type": "string",
                "example": "string"
              },
              "idempotencyKey": {
                "type": "string",
                "example": "string"
              },
              "requestedAt": {
                "type": "string",
                "example": "string"
              },
              "sourceSystem": {
                "type": "string",
                "example": "string"
              },
              "sourceApplication": {
                "type": "string",
                "example": "string"
              },
              "channel": {
                "type": "object",
                "properties": {
                  "channelId": {
                    "type": "string",
                    "example": "string"
                  },
                  "channelType": {
                    "type": "string",
                    "example": "string"
                  },
                  "deviceId": {
                    "type": "string",
                    "example": "string"
                  }
                },
                "example": "string"
              }
            },
            "example": {
              "requestId": "cbbcae06-7013-5c52-948a-c1169e686f69",
              "correlationId": "0f8a16bb-1cb4-558a-9b72-0a149f16b238",
              "idempotencyKey": "91563298-58b5-5b16-876b-3d006a294172",
              "requestedAt": "2026-09-15T14:30:00Z",
              "sourceSystem": "DIGITAL_BANKING",
              "sourceApplication": "MOBILE_APP",
              "channel": {
                "channelId": "MOBILE-US",
                "channelType": "MOBILE",
                "deviceId": "DEV-579557"
              }
            }
          }
        },
        "example": {
          "reviewReason": "STANDARD",
          "reviewScope": [
            "STANDARD"
          ],
          "assignedReviewerId": "STANDARD",
          "dueAt": "2026-08-11T12:00:00Z",
          "requestContext": {
            "requestId": "cbbcae06-7013-5c52-948a-c1169e686f69",
            "correlationId": "0f8a16bb-1cb4-558a-9b72-0a149f16b238",
            "idempotencyKey": "91563298-58b5-5b16-876b-3d006a294172",
            "requestedAt": "2026-09-15T14:30:00Z",
            "sourceSystem": "DIGITAL_BANKING",
            "sourceApplication": "MOBILE_APP",
            "channel": {
              "channelId": "MOBILE-US",
              "channelType": "MOBILE",
              "deviceId": "DEV-579557"
            }
          }
        }
      },
      "CreateBankingEnterpriseServicesSecurityAssuranceReviewResponse_202": {
        "type": "object",
        "properties": {
          "actionReference": {
            "type": "string",
            "example": "STANDARD"
          },
          "actionType": {
            "type": "string",
            "example": "STANDARD"
          },
          "status": {
            "type": "string",
            "example": "ACTIVE"
          },
          "processedAt": {
            "type": "string",
            "example": "2026-08-11T12:00:00Z"
          },
          "metadata": {
            "type": "object",
            "properties": {
              "responseId": {
                "type": "string",
                "example": "string"
              },
              "correlationId": {
                "type": "string",
                "example": "string"
              },
              "generatedAt": {
                "type": "string",
                "example": "string"
              },
              "processingRegion": {
                "type": "string",
                "example": "string"
              }
            },
            "example": {
              "responseId": "e84652f1-4d45-5c40-bed5-ea3a3a9e56eb",
              "correlationId": "0f8a16bb-1cb4-558a-9b72-0a149f16b238",
              "generatedAt": "2026-09-15T14:30:00Z",
              "processingRegion": "us-east-1"
            }
          }
        },
        "example": {
          "actionReference": "STANDARD",
          "actionType": "STANDARD",
          "status": "ACTIVE",
          "processedAt": "2026-08-11T12:00:00Z",
          "metadata": {
            "responseId": "e84652f1-4d45-5c40-bed5-ea3a3a9e56eb",
            "correlationId": "0f8a16bb-1cb4-558a-9b72-0a149f16b238",
            "generatedAt": "2026-09-15T14:30:00Z",
            "processingRegion": "us-east-1"
          }
        }
      }
    },
    "parameters": {
      "x-mock-response": {
        "name": "x-mock-response",
        "in": "header",
        "description": "Controls x-mock-response response status",
        "required": false,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "enum": [
            "MICROSERVICE_PROD_202"
          ]
        }
      },
      "securityAssuranceId": {
        "name": "securityAssuranceId",
        "in": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string"
        }
      }
    },
    "headers": {
      "X-Endpoint-Id": {
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "example": "security-assurance-review-security-assurance"
        },
        "example": "security-assurance-review-security-assurance"
      },
      "X-Runtime-App": {
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "example": "enterprise-support"
        },
        "example": "enterprise-support"
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}