{
  "openapi": "3.0.1",
  "info": {
    "title": "MICROSERVICE-PROD-Update Banking Business Control Organization Direction By Organization Direction Id-v5-spec",
    "description": "MICROSERVICE-PROD-Update Banking Business Control Organization Direction By Organization Direction Id-v5-spec",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://prod-workspace-pwmw.apiwiz.io",
      "description": "Sandbox server",
      "variables": {},
      "x-schema": "https://",
      "x-name": "Sandbox server",
      "x-environmentName": "Sandbox",
      "x-hide": false,
      "x-environmentId": "6a7f52236ae9a15654cd5721",
      "x-basePath": "/"
    },
    {
      "url": "http://35.162.152.203:9008",
      "description": "PROD",
      "variables": {},
      "x-schema": "http://",
      "x-name": "PROD",
      "x-environmentName": "PROD",
      "x-hide": false,
      "x-environmentId": "6a784eac1d7e36108cc3cb0c",
      "x-basePath": "/"
    }
  ],
  "paths": {
    "/v5/banking/business-control/organization-direction/{organizationDirectionId}": {
      "patch": {
        "operationId": "updateBankingBusinessControlOrganizationDirectionByOrganizationDirectionId",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-mock-response"
          },
          {
            "$ref": "#/components/parameters/organizationDirectionId"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateBankingBusinessControlOrganizationDirectionByOrganizationDirectionIdRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200Description",
            "headers": {
              "X-Endpoint-Id": {
                "$ref": "#/components/headers/X-Endpoint-Id"
              },
              "X-Runtime-App": {
                "$ref": "#/components/headers/X-Runtime-App"
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateBankingBusinessControlOrganizationDirectionByOrganizationDirectionIdResponse_200"
                }
              }
            }
          }
        },
        "callbacks": {},
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "servers": []
      },
      "servers": [],
      "parameters": []
    }
  },
  "components": {
    "schemas": {
      "UpdateBankingBusinessControlOrganizationDirectionByOrganizationDirectionIdRequest": {
        "type": "object",
        "properties": {
          "changes": {
            "type": "object",
            "properties": {
              "businessUnitId": {
                "type": "string",
                "example": "string"
              },
              "costCenter": {
                "type": "string",
                "example": "string"
              },
              "planningPeriod": {
                "type": "string",
                "example": "string"
              }
            },
            "example": {
              "businessUnitId": "STANDARD",
              "costCenter": "STANDARD",
              "planningPeriod": "STANDARD"
            }
          },
          "changeReason": {
            "type": "string",
            "example": "STANDARD"
          },
          "effectiveAt": {
            "type": "string",
            "example": "2026-09-15T14:30:00Z"
          },
          "requestedBy": {
            "type": "string",
            "example": "STANDARD"
          },
          "requestContext": {
            "type": "object",
            "properties": {
              "requestId": {
                "type": "string",
                "example": "string"
              },
              "correlationId": {
                "type": "string",
                "example": "string"
              },
              "idempotencyKey": {
                "type": "string",
                "example": "string"
              },
              "requestedAt": {
                "type": "string",
                "example": "string"
              },
              "sourceSystem": {
                "type": "string",
                "example": "string"
              },
              "sourceApplication": {
                "type": "string",
                "example": "string"
              },
              "channel": {
                "type": "object",
                "properties": {
                  "channelId": {
                    "type": "string",
                    "example": "string"
                  },
                  "channelType": {
                    "type": "string",
                    "example": "string"
                  },
                  "deviceId": {
                    "type": "string",
                    "example": "string"
                  }
                },
                "example": "string"
              }
            },
            "example": {
              "requestId": "a27c40b6-3375-5d9b-a82a-422a58bdb871",
              "correlationId": "ec3f7077-9512-5f43-8d27-85cc2ec43d8e",
              "idempotencyKey": "ccd40b52-d878-55d0-a840-6f86cb240d3c",
              "requestedAt": "2026-09-15T14:30:00Z",
              "sourceSystem": "DIGITAL_BANKING",
              "sourceApplication": "MOBILE_APP",
              "channel": {
                "channelId": "MOBILE-US",
                "channelType": "MOBILE",
                "deviceId": "DEV-140786"
              }
            }
          }
        },
        "example": {
          "changes": {
            "businessUnitId": "STANDARD",
            "costCenter": "STANDARD",
            "planningPeriod": "STANDARD"
          },
          "changeReason": "STANDARD",
          "effectiveAt": "2026-09-15T14:30:00Z",
          "requestedBy": "STANDARD",
          "requestContext": {
            "requestId": "a27c40b6-3375-5d9b-a82a-422a58bdb871",
            "correlationId": "ec3f7077-9512-5f43-8d27-85cc2ec43d8e",
            "idempotencyKey": "ccd40b52-d878-55d0-a840-6f86cb240d3c",
            "requestedAt": "2026-09-15T14:30:00Z",
            "sourceSystem": "DIGITAL_BANKING",
            "sourceApplication": "MOBILE_APP",
            "channel": {
              "channelId": "MOBILE-US",
              "channelType": "MOBILE",
              "deviceId": "DEV-140786"
            }
          }
        }
      },
      "UpdateBankingBusinessControlOrganizationDirectionByOrganizationDirectionIdResponse_200": {
        "type": "object",
        "properties": {
          "version": {
            "type": "integer",
            "format": "int32",
            "example": 1
          },
          "status": {
            "type": "string",
            "example": "ACTIVE"
          },
          "updatedAt": {
            "type": "string",
            "example": "2026-09-15T14:30:00Z"
          },
          "metadata": {
            "type": "object",
            "properties": {
              "responseId": {
                "type": "string",
                "example": "string"
              },
              "correlationId": {
                "type": "string",
                "example": "string"
              },
              "generatedAt": {
                "type": "string",
                "example": "string"
              },
              "processingRegion": {
                "type": "string",
                "example": "string"
              }
            },
            "example": {
              "responseId": "8443ef1e-2fe3-51cb-9c17-fd8a5b169127",
              "correlationId": "ec3f7077-9512-5f43-8d27-85cc2ec43d8e",
              "generatedAt": "2026-09-15T14:30:00Z",
              "processingRegion": "us-east-1"
            }
          }
        },
        "example": {
          "version": 1,
          "status": "ACTIVE",
          "updatedAt": "2026-09-15T14:30:00Z",
          "metadata": {
            "responseId": "8443ef1e-2fe3-51cb-9c17-fd8a5b169127",
            "correlationId": "ec3f7077-9512-5f43-8d27-85cc2ec43d8e",
            "generatedAt": "2026-09-15T14:30:00Z",
            "processingRegion": "us-east-1"
          }
        }
      }
    },
    "parameters": {
      "x-mock-response": {
        "name": "x-mock-response",
        "in": "header",
        "description": "Controls x-mock-response response status",
        "required": false,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "enum": [
            "MICROSERVICE_PROD_200"
          ]
        }
      },
      "organizationDirectionId": {
        "name": "organizationDirectionId",
        "in": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string"
        }
      }
    },
    "headers": {
      "X-Endpoint-Id": {
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "example": "organization-direction-update-organization-direction"
        },
        "example": "organization-direction-update-organization-direction"
      },
      "X-Runtime-App": {
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "example": "enterprise-support"
        },
        "example": "enterprise-support"
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}